In [1]:
import numpy as np

# 1. ndarray
- **np.array**(list or tuple)

In [2]:
arr = np.array([1,2,3])
lst = [1,2,3]

In [3]:
# arr는 공백으로 구분
# lst는 구분점으로 구분

print(arr)
print(lst)

[1 2 3]
[1, 2, 3]


In [4]:
print(arr[1], type(arr[1]))
print(lst[1], type(lst[1]))

2 <class 'numpy.int64'>
2 <class 'int'>


In [5]:
arr = np.array([1,2.0, '3'])
lst = [1,2.0,'3']

In [6]:
# ndarray 요소는 하나의 데이터 타입만을 갖는다
# 포함된 모든 요소를 표현할 수 있는 하나의 데이터타입이 결정됨
# - int, float가 함께 포함된 경우, dtype은 float type
# - str이 포함된 경우, dtype은 str type

print(arr)
print(lst)

['1' '2.0' '3']
[1, 2.0, '3']


In [7]:
print(arr[2], type(arr[1]))
print(lst[2], type(lst[2]))

3 <class 'numpy.str_'>
3 <class 'str'>


# 2. ndim과 shape
- **ndarray.ndim**: ndarray의 차원(dim)을 변환
- **ndarray.shape**: ndarray의 형태을 반환 (tuple type)

In [8]:
mat = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
arr = np.array([1,2,3])

In [9]:
# ndarray를 출력했을 때, 열린 대괄호 또는 닫힌 대괄호의 수가 ndim과 동일함

print(mat)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3]


In [10]:
print(mat.ndim)
print(arr.ndim)

2
1


In [11]:
# shape은 각 차원이 몇개의 요소로 구성되어 있는지를 보여줌
# 주로 다르게 되는 2차원 ndarray의 경우, shape은 (행의 수, 열의 수)를 의미함
# ndim = 1인 ndarray의 기준
# -> shape은 tuple 타입을 반환하며, tuple의 원소 수는 ndim과 동일
# -> shape이 반환하는 (a,b)에서 a는 행(row), b는 열(column)의 수를 의미함

print(arr.shape)
print(mat.shape)

(3,)
(3, 4)


In [12]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3]])
arr3 = np.array([[1],[2],[3]])

In [13]:
print(arr1)
print(arr2)
print(arr3)

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [14]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(1, 3)
(3, 1)


# 3. Indexing과 Slicing
- **indexing**: ndarray[a,b], 원소 하나를 지정
- **slicing**: ndarray[a:b, c:d], 범위를 통해 ndarray의 일부를 지정
>- a:b   index a ~ b - 1까지
>- :b    index a ~ b - 1까지
>- a:    index a ~
>- :     index 전체
>- -1    마지막 index

In [15]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
# index는 0부터 시작함
# [1,2]는 index 1인 행(두번째 행), index 2인 열(세번째 열) 위치의 원소를 의미
print(mat[1,2])

7


In [17]:
# slicing - 두번째 ~ 세번째 행의 첫번째 ~ 세번째 열
# [[5,6,7],
#  [9,10,11]]

print(mat[1:3,0:3])

print()

# 행은 두번째부터 마지막 행까지 포함하므로 아래와 같이 표현 가능

print(mat[1:,0:3])

print()

# 열은 첫번째부터 포함하므로 아래와 같이 표현 가능

print(mat[1:, :3])

[[ 5  6  7]
 [ 9 10 11]]

[[ 5  6  7]
 [ 9 10 11]]

[[ 5  6  7]
 [ 9 10 11]]


In [18]:
# -1은 마지막 index를 의미하므로 1:-1로 표기할 경우, 마지막 index를 포함하지 않음
print(mat[1:-1, :3])
#마지막 행이 제외됨

[[5 6 7]]


In [19]:
# ndarray[정수, 정수]: 0차원 반환(하나의 원소 반환)
# ndarray[정수, 범위] 또는 ndarray[범위, 정수]: 1차원 ndarray 반환
# ndarray[범위, 범위]: 2차원 ndarray 반환

In [20]:
# 아래는 모두 index = 1인 행(두번째 행), index = 2인 열(세번째 열)의 값을 가리킴
# 일반적으로 주어진 2차원 데이터에서 마지막 열이 y(target), 마지막 열을 제외한 나머지 열이 x(feature)가 되는 경우가 많음

print(mat[1,2], mat[1,2].shape)
print(mat[1:2,2], mat[1:2,2].shape)
print(mat[1,2:3], mat[1,2:3].shape)
print(mat[1:2,2:3], mat[1:2,2:3].shape)

7 ()
[7] (1,)
[7] (1,)
[[7]] (1, 1)


# 4. reshape
- ndarray.reshape(shape): 입력된 shape의 형태로 변환
- ndarray의 원소 수와 변환 후의 원소 수는 반드시 동일해야 함
- (3,4) shape의 ndarray를 (5,2) shape으로는 변환할 수 없음
- reshape 의 값 중, 하나를 -1로 지정하면, 원소 값에 맞춰서 자동으로 계산 됨
- 원소 수가 12개인 mat에 대해 mat.reshape(4,-1)로 지정하면 12개 원소 수에 맞춰 자동으로 mat.reshape(4,3)이 실행됨
- 단, 반드시 -1은 하나의 차원에 대해서만 적용해야 함. mat.reshape(-1,-1)은 오류 발생

In [21]:
# (3,4)인 mat을 (2,6)으로 변환
mat.reshape(2,6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
# 2차원인 mat을 1차원으로 변경
# print(mat.reshape(-1))
print(mat.reshape(12))

# 1차원인 arr을 2차원으로 변경
print(arr.reshape(3,1))
print(arr.reshape(-1,1)) # 1d array를 n행 1열 2d array로 변환
print(arr.reshape(1,3))
print(arr.reshape(1,-1)) # 1d array를 1행 n열 2d array로 변환

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
[[1 2 3]]
[[1 2 3]]


# 5. delete와 concatenate
- np.delete(ndarray, index, axis): 행 또는 열 삭제
> - index: 삭제할 행 또는 열의 index
> - axis = 0: 행 삭제, axis = 1: 열 삭제
- np.concatenate((arr1, arr2)m axis): 두 ndarray 결합
> - axis = 0: 상하 결합, axis = 1: 좌우 결합

In [23]:
mat1 = np.array([[1,2,3], [4,5,6]])
mat2 = np.array([[7,8,9],[10,11,12]])

print(mat1, mat1.shape)
print(mat2, mat2.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[ 7  8  9]
 [10 11 12]] (2, 3)


In [24]:
# mat1의 두번째 열 (index = 1, axis = 1) 삭제

np.delete(mat1, 1, axis = 1)

array([[1, 3],
       [4, 6]])

In [25]:
# mat2의 첫번째 행(index = 0, axis = 0) 삭제
# 삭제 후 차원은 변경되지 않는다

np.delete(mat2, 0, axis = 0)

array([[10, 11, 12]])

In [26]:
# mat1과 mat2의 상하결합 (axis = 0)

np.concatenate((mat1,mat2), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
# mat1과 mat2의 좌우결합 (axis = 1)

np.concatenate((mat1,mat2), axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [28]:
# mat.shape = (a,b): a가 axis = 0, b가 axis = 1을 의미함
# 즉, axis = 0은 행, axis = 1은 열을 의미함
# delete의 axis = 0은 행의 감소(행 삭제), axis = 1은 열의 감소(열 삭제)를 의미함
# concatenate의 axis = 0은 행의 증가(상하 결합), axis = 1은 열의 증가(좌우 결합)를 의미함